### ISSUE TITLE
启用插件后和图片的居中显示有冲突

### ISSUE THREAD

**Issue by Ryoga1016** [Yaozhuwa/AttachFlow#22]
具体情况为，当启用插件后，原居中显示的图片只要鼠标移动上去就会变成左对齐，我尝试过关闭插件重启ob后能正常居中。

有个情况是个例外，当图片加了标题和尺寸后，就能正常居中了。

![GIF 240423 173020](https://github.com/Yaozhuwa/AttachFlow/assets/49177478/b7a4806a-6ab6-4dd0-bf30-5428438e54bf)

**Comment by Yaozhuwa** [comment]
无法复现：
![iShot_2024-04-24_12 18 43](https://github.com/Yaozhuwa/AttachFlow/assets/28787183/02f7f7ca-0615-444e-80c3-1b21f7fedac0)

请检查：
1. 插件是否更新到最新版本
2. 你的图片居中 CSS 选择器（本插件在光标移动时添加一个类名，一般不会对别的CSS有冲突）
3. 其他插件问题

**Comment by Yaozhuwa** [comment]
此外， #17 也请回复反馈下

**Comment by yooboh** [comment]
> 无法复现： ![iShot_2024-04-24_12 18 43](https://private-user-images.githubusercontent.com/28787183/325078750-02f7f7ca-0615-444e-80c3-1b21f7fedac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA5ODUsIm5iZiI6MTcxNDEzMDY4NSwicGF0aCI6Ii8yODc4NzE4My8zMjUwNzg3NTAtMDJmN2Y3Y2EtMDYxNS00NDRlLTgwYzMtMWIyMWY3ZmVkYWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2Y0YWU1ODNiZTU1OWZjMWZkYWRlYzQ2N2Y4ZWUzNjFhNmUyMGE4MTNkYThlMWM2NDdmYzYyYjZiNTg0YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4Q6xV4kKCU8J7Z4rqHAsjicfDNO-Z7SZVcWmSi1dn0) [ ![iShot_2024-04-24_12 18 43](https://private-user-images.githubusercontent.com/28787183/325078750-02f7f7ca-0615-444e-80c3-1b21f7fedac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA5ODUsIm5iZiI6MTcxNDEzMDY4NSwicGF0aCI6Ii8yODc4NzE4My8zMjUwNzg3NTAtMDJmN2Y3Y2EtMDYxNS00NDRlLTgwYzMtMWIyMWY3ZmVkYWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2Y0YWU1ODNiZTU1OWZjMWZkYWRlYzQ2N2Y4ZWUzNjFhNmUyMGE4MTNkYThlMWM2NDdmYzYyYjZiNTg0YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4Q6xV4kKCU8J7Z4rqHAsjicfDNO-Z7SZVcWmSi1dn0) ](https://private-user-images.githubusercontent.com/28787183/325078750-02f7f7ca-0615-444e-80c3-1b21f7fedac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA5ODUsIm5iZiI6MTcxNDEzMDY4NSwicGF0aCI6Ii8yODc4NzE4My8zMjUwNzg3NTAtMDJmN2Y3Y2EtMDYxNS00NDRlLTgwYzMtMWIyMWY3ZmVkYWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2Y0YWU1ODNiZTU1OWZjMWZkYWRlYzQ2N2Y4ZWUzNjFhNmUyMGE4MTNkYThlMWM2NDdmYzYyYjZiNTg0YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4Q6xV4kKCU8J7Z4rqHAsjicfDNO-Z7SZVcWmSi1dn0) [ ](https://private-user-images.githubusercontent.com/28787183/325078750-02f7f7ca-0615-444e-80c3-1b21f7fedac0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzA5ODUsIm5iZiI6MTcxNDEzMDY4NSwicGF0aCI6Ii8yODc4NzE4My8zMjUwNzg3NTAtMDJmN2Y3Y2EtMDYxNS00NDRlLTgwYzMtMWIyMWY3ZmVkYWMwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1N2Y0YWU1ODNiZTU1OWZjMWZkYWRlYzQ2N2Y4ZWUzNjFhNmUyMGE4MTNkYThlMWM2NDdmYzYyYjZiNTg0YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4Q6xV4kKCU8J7Z4rqHAsjicfDNO-Z7SZVcWmSi1dn0)
> 
> 请检查：
> 
> 1. 插件是否更新到最新版本
> 2. 你的图片居中 CSS 选择器（本插件在光标移动时添加一个类名，一般不会对别的CSS有冲突）
> 3. 其他插件问题

我也遇到了完全一样的问题，我用的border主题，在style setteings插件中选中图片居中显示并开启这个插件后就会发生冲突，并且原本是正常的，我记得是从0.4版本开始突然冲突的，原本我下的0.3版本没有冲突

**Comment by Yaozhuwa** [comment]
> 我也遇到了完全一样的问题，我用的border主题，在style setteings插件中选中图片居中显示并开启这个插件后就会发生冲突，并且原本是正常的，我记得是从0.4版本开始突然冲突的，原本我下的0.3版本没有冲突

@yooboh 感谢精准的问题描述，可以复现，原因在于其CSS冲突了。

找到border主题如下CSS代码：
```css
/*  image center align */
.img-center-align .print :is(.markdown-preview-view, .markdown-rendered) img:not([class]),
.img-center-align .markdown-preview-view img:not([class]),
.img-center-align .markdown-source-view img:not([class]) {
    display: block;
    margin-left: auto !important;
    margin-right: auto !important;
}
```
去掉 `:not([class])`， 修改成：
```css
.img-center-align .print :is(.markdown-preview-view, .markdown-rendered),
.img-center-align .markdown-preview-view img,
.img-center-align .markdown-source-view img{
    display: block;
    margin-left: auto !important;
    margin-right: auto !important;
}
```
